"""add email validation and unique constraint to dealerships

Revision ID: a957a214e02b
Revises: 002
Create Date: 2025-11-10 09:04:42.629091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a957a214e02b'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_automation_dealership', table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index('idx_vehicles_dealership', table_name='vehicles')
    op.drop_index('idx_vehicles_status', table_name='vehicles')
    op.drop_table('vehicles')
    op.alter_column('conversations', 'message_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_conversations_created', table_name='conversations')
    op.drop_index('idx_conversations_lead', table_name='conversations')
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_lead_id'), 'conversations', ['lead_id'], unique=False)
    op.alter_column('dealerships', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('dealerships', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('dealerships', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'starter'::character varying"))
    op.drop_constraint('dealerships_clerk_org_id_key', 'dealerships', type_='unique')
    op.drop_index('idx_dealerships_clerk_org', table_name='dealerships')
    op.create_index(op.f('ix_dealerships_clerk_org_id'), 'dealerships', ['clerk_org_id'], unique=True)
    op.create_unique_constraint(None, 'dealerships', ['email'])
    op.create_check_constraint(
        'valid_dealership_email',
        'dealerships',
        "email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'"
    )
    op.alter_column('leads', 'source_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('leads', 'initial_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_leads_created', table_name='leads')
    op.drop_index('idx_leads_dealership', table_name='leads')
    op.drop_index('idx_leads_email', table_name='leads')
    op.drop_index('idx_leads_source', table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_customer_email'), 'leads', ['customer_email'], unique=False)
    op.create_index(op.f('ix_leads_dealership_id'), 'leads', ['dealership_id'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.drop_index('idx_users_clerk', table_name='users')
    op.drop_index('idx_users_dealership', table_name='users')
    op.drop_constraint('users_clerk_user_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_dealership_id'), 'users', ['dealership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_dealership_id'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_unique_constraint('users_clerk_user_id_key', 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_users_dealership', 'users', ['dealership_id'], unique=False)
    op.create_index('idx_users_clerk', 'users', ['clerk_user_id'], unique=False)
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_dealership_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index('idx_leads_source', 'leads', ['source'], unique=False)
    op.create_index('idx_leads_email', 'leads', ['customer_email'], unique=False)
    op.create_index('idx_leads_dealership', 'leads', ['dealership_id'], unique=False)
    op.create_index('idx_leads_created', 'leads', ['created_at'], unique=False)
    op.alter_column('leads', 'initial_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('leads', 'source_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('valid_dealership_email', 'dealerships', type_='check')
    op.drop_constraint(None, 'dealerships', type_='unique')
    op.drop_index(op.f('ix_dealerships_clerk_org_id'), table_name='dealerships')
    op.create_index('idx_dealerships_clerk_org', 'dealerships', ['clerk_org_id'], unique=False)
    op.create_unique_constraint('dealerships_clerk_org_id_key', 'dealerships', ['clerk_org_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('dealerships', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'starter'::character varying"))
    op.alter_column('dealerships', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('dealerships', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_conversations_lead_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.create_index('idx_conversations_lead', 'conversations', ['lead_id'], unique=False)
    op.create_index('idx_conversations_created', 'conversations', ['created_at'], unique=False)
    op.alter_column('conversations', 'message_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('dealership_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vin', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'available'::character varying"), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fuel_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('listing_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name='vehicles_dealership_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey')
    )
    op.create_index('idx_vehicles_status', 'vehicles', ['status'], unique=False)
    op.create_index('idx_vehicles_dealership', 'vehicles', ['dealership_id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('dealership_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], name='automation_rules_dealership_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='automation_rules_pkey')
    )
    op.create_index('idx_automation_dealership', 'automation_rules', ['dealership_id'], unique=False)
    # ### end Alembic commands ###
